### ISSUE TITLE
missing obstack.h

### ISSUE THREAD

**Issue by ShaharHD** [DIGImend/hidrd#21]
Trying to build on Mac (10.14.4) and keep getting short on `obstack.h`

I've modified the makefile to include one (from another mac ports) - but I'm now failing on this error:
```
Making all in util
  CC       obstack.lo
obstack.c:301:5: error: arithmetic on a null pointer treated as a cast from integer to pointer is a GNU extension [-Werror,-Wnull-pointer-arithmetic]
    __INT_TO_PTR ((__PTR_TO_INT (new_chunk->contents) + h->alignment_mask)
```

I can try and disable the warning, but is it safe?

**Comment by lechium** [comment]
same issue +1

**Comment by spbnick** [comment]
Never had access to a Mac, so can't reproduce, but if somebody gives me that obstack.c, I can try to figure out if it's safe. Otherwise, I would say using obstack in hidrd is an overkill and I would welcome a patch getting rid of it.

**Comment by ShaharHD** [comment]
@spbnick this is the file I tried to use
https://github.com/iannakin/macports/tree/master/sysutils/anacron/files

**Comment by lechium** [comment]
i grabbed on from cctools so im not even sure if its an appropriate copy to try to use. im not familiar with what obstack does in the first place so a patch for this would be out of my depth personally! i also cant even get it to build with the obstack so thats my latest obstacle.

[obstack-cctools.zip](https://github.com/DIGImend/hidrd/files/4586370/obstack-cctools.zip)

**Comment by ShaharHD** [comment]
I just grabbed the one from here: https://github.com/abgoyal-archive/OT_W969/tree/b96e54d94ac7dd3275d42101d45c1b1a5eb69b4c/external/bison/lib this time to try and recreate the issue. now I'm failing on
```shell
  CC       hidrd_convert-hidrd-convert.o
hidrd-convert.c:235:31: error: use of undeclared identifier 'program_invocation_short_name'
        usage_formats(stderr, program_invocation_short_name);
                              ^
hidrd-convert.c:242:31: error: use of undeclared identifier 'program_invocation_short_name'
        usage_formats(stderr, program_invocation_short_name);
                              ^
hidrd-convert.c:258:31: error: use of undeclared identifier 'program_invocation_short_name'
        usage_formats(stderr, program_invocation_short_name);
                              ^
hidrd-convert.c:265:31: error: use of undeclared identifier 'program_invocation_short_name'
        usage_formats(stderr, program_invocation_short_name);
                              ^
hidrd-convert.c:494:31: error: use of undeclared identifier 'program_invocation_short_name'
                usage(stdout, program_invocation_short_name);
                              ^
hidrd-convert.c:498:39: error: use of undeclared identifier 'program_invocation_short_name'
                usage_formats(stdout, program_invocation_short_name);
                                      ^
hidrd-convert.c:514:31: error: use of undeclared identifier 'program_invocation_short_name'
                usage(stderr, program_invocation_short_name);
                              ^
hidrd-convert.c:532:31: error: use of undeclared identifier 'program_invocation_short_name'
                usage(stderr, program_invocation_short_name);
                              ^
hidrd-convert.c:544:23: error: use of undeclared identifier 'program_invocation_short_name'
        usage(stderr, program_invocation_short_name);
                      ^
hidrd-convert.c:550:23: error: use of undeclared identifier 'program_invocation_short_name'
        usage(stderr, program_invocation_short_name);
                      ^
hidrd-convert.c:556:23: error: use of undeclared identifier 'program_invocation_short_name'
        usage(stderr, program_invocation_short_name);
                      ^
hidrd-convert.c:562:23: error: use of undeclared identifier 'program_invocation_short_name'
        usage(stderr, program_invocation_short_name);
                      ^
```

**Comment by ShaharHD** [comment]
@lechium @spbnick got it working!

**Another update**
with the files @lechium sent, the fix was fairly simple to make it finish the build.
I'll create a Fork and a PR later today for you to review

The issue is now that it is looking for `__obstack_begin` which means I need to get the obstack as a static library into the code.

Working on it, will fork and create a PR

**Comment by ShaharHD** [comment]
@lechium @spbnick Created PR #24

**Comment by ShaharHD** [comment]
PR #24 updated with removing obstack all together
